// Demo fixture, split out of ./approval.ts to keep the Book1 rules module under its
// 700-line guardrail — this is ~200 lines of pure demo data with no logic in it, sitting
// in the file CLAUDE.md calls the "Rules center". Same re-export pattern this branch
// already used for memo-line-items and memo-revision.
//
// The MemoRecord import MUST stay `import type`: approval.ts re-exports seedMemos from
// here, so a value import back into approval.ts would create a real runtime cycle.
// Nothing in this file may import a *value* from ./approval.
//
// CLAUDE.md's "seed/demo content is not production data — clean before external trial"
// item is now a single-file deletion.
import type { MemoRecord } from "./approval";

export const seedMemos: MemoRecord[] = [
  {
    // Pending at Manager — just submitted today; good for "new request" demo
    id: "EM-2026-001",
    title: "ขออนุมัติจัดซื้ออุปกรณ์สำนักงาน",
    requester: "ปุณณวิช ภูประเสริฐ",
    department: "HR&GA",
    category: "general-purchase",
    amount: 9200,
    description: "ขออนุมัติจัดซื้อเก้าอี้ทำงานเออร์โกโนมิก 4 ตัว และโต๊ะทำงาน 2 ตัว เพื่อรองรับพนักงานใหม่ฝ่าย HR&GA ที่จะเข้างานในเดือนมิถุนายน 2026",
    budgetStatus: "in-budget",
    accountCode: "5101-001",
    budgetPlan: 20000,
    budgetUsed: 8500,
    status: "pending",
    workflowState: "Issued",
    currentStep: "Manager / Top Section",
    recommendedFinalApprover: "Manager / Top Section",
    recommendedRoute: ["Manager / Top Section"],
    selectedRoute: ["Manager / Top Section"],
    routeMode: "recommended",
    cycleHours: 4,
    createdAt: "09 Jun 2026 09:15",
    updatedAt: "09 Jun 2026 09:15",
  },
  {
    // Pending at GM — mid-approval; good for showing workflow progress
    id: "EM-2026-002",
    title: "ขออนุมัติซ่อมบำรุงระบบไฟฟ้าโรงงาน",
    requester: "สมศักดิ์ วงศ์ไพบูลย์",
    department: "GA",
    category: "service-contract",
    amount: 45000,
    description: "ขออนุมัติค่าบริการตรวจสอบและซ่อมแซมระบบไฟฟ้าแรงสูงในพื้นที่โรงงาน 2 โดยบริษัทผู้รับเหมาที่ได้รับการรับรอง เพื่อความปลอดภัยในการปฏิบัติงานตามมาตรฐาน ISO 45001",
    budgetStatus: "in-budget",
    accountCode: "5301-002",
    budgetPlan: 100000,
    budgetUsed: 22000,
    status: "pending",
    workflowState: "Checked",
    currentStep: "General Manager",
    recommendedFinalApprover: "General Manager",
    recommendedRoute: ["Manager / Top Section", "General Manager"],
    selectedRoute: ["Manager / Top Section", "General Manager"],
    routeMode: "recommended",
    cycleHours: 20,
    createdAt: "07 Jun 2026 10:00",
    updatedAt: "08 Jun 2026 08:10",
  },
  {
    // Pending at MD — high-value asset; star of the Executive Review demo
    id: "EM-2026-003",
    title: "ขออนุมัติจัดซื้อเครื่องอัดยางอัตโนมัติ",
    requester: "สุภาพร เจริญสุข",
    department: "PD",
    category: "fixed-asset",
    amount: 240000,
    description: "ขออนุมัติจัดซื้อเครื่องอัดยางอัตโนมัติ รุ่น CAR-X500 จำนวน 1 เครื่อง เพื่อเพิ่มกำลังการผลิตในไลน์ยางกันกระแทก รองรับออเดอร์ที่คาดว่าจะเพิ่มขึ้น 35% ในไตรมาส 3 ปี 2026",
    budgetStatus: "in-budget",
    accountCode: "6001-001",
    budgetPlan: 500000,
    budgetUsed: 180000,
    status: "pending",
    workflowState: "Checked",
    currentStep: "Managing Director",
    recommendedFinalApprover: "Managing Director",
    recommendedRoute: ["Manager / Top Section", "General Manager", "Managing Director"],
    selectedRoute: ["Manager / Top Section", "General Manager", "Managing Director"],
    routeMode: "recommended",
    cycleHours: 28,
    createdAt: "05 Jun 2026 08:00",
    updatedAt: "08 Jun 2026 14:30",
  },
  {
    // Approved — raw material following production plan
    id: "EM-2026-004",
    title: "ขออนุมัติจัดซื้อยางธรรมชาติตามแผนการผลิต",
    requester: "สุภาพร เจริญสุข",
    department: "PD",
    category: "raw-material",
    amount: 68000,
    description: "ขออนุมัติจัดซื้อยางธรรมชาติเกรด RSS3 จำนวน 2,000 กก. ตามแผนการผลิตประจำสัปดาห์ที่ 23–24 เพื่อรองรับออเดอร์ลูกค้าหลัก (Toyota Supplier)",
    budgetStatus: "in-budget",
    accountCode: "4001-001",
    budgetPlan: 800000,
    budgetUsed: 420000,
    followsProductionPlan: true,
    status: "approved",
    workflowState: "Approved",
    currentStep: "General Manager",
    recommendedFinalApprover: "General Manager",
    recommendedRoute: ["Manager / Top Section", "General Manager"],
    selectedRoute: ["Manager / Top Section", "General Manager"],
    routeMode: "recommended",
    cycleHours: 8,
    createdAt: "04 Jun 2026 07:30",
    updatedAt: "04 Jun 2026 15:45",
  },
  {
    // Approved — IT software renewal; shows full MD-tier completed flow
    id: "EM-2026-005",
    title: "ขออนุมัติต่ออายุซอฟต์แวร์ Microsoft 365",
    requester: "ปุณณวิช ภูประเสริฐ",
    department: "IT",
    category: "service-contract",
    amount: 76000,
    description: "ขออนุมัติต่ออายุสัญญาซอฟต์แวร์ Microsoft 365 Business สำหรับพนักงาน 38 คน ประจำปี 2026–2027 เพื่อความต่อเนื่องในการทำงานและการเข้าถึงอีเมล OneDrive และ Teams",
    budgetStatus: "in-budget",
    accountCode: "5201-001",
    budgetPlan: 100000,
    budgetUsed: 76000,
    status: "approved",
    workflowState: "Approved",
    currentStep: "Managing Director",
    recommendedFinalApprover: "Managing Director",
    recommendedRoute: ["Manager / Top Section", "General Manager", "Managing Director"],
    selectedRoute: ["Manager / Top Section", "General Manager", "Managing Director"],
    routeMode: "recommended",
    cycleHours: 16,
    createdAt: "02 Jun 2026 09:00",
    updatedAt: "03 Jun 2026 11:00",
  },
  {
    // Returned — missing quotation docs; good for revision flow demo
    id: "EM-2026-006",
    title: "ขออนุมัติจัดงานกิจกรรมพนักงานประจำปี",
    requester: "นัดดา หาญกล้า",
    department: "HR&GA",
    category: "general-purchase",
    amount: 28000,
    description: "ขออนุมัติงบประมาณจัดงาน Company Outing ประจำปี 2026 สำหรับพนักงาน 85 คน รวมค่าสถานที่ อาหาร และกิจกรรมสันทนาการ",
    budgetStatus: "in-budget",
    accountCode: "5102-001",
    budgetPlan: 50000,
    budgetUsed: 0,
    status: "returned",
    workflowState: "Issued",
    currentStep: "Manager / Top Section",
    recommendedFinalApprover: "General Manager",
    recommendedRoute: ["Manager / Top Section", "General Manager"],
    selectedRoute: ["Manager / Top Section", "General Manager"],
    routeMode: "recommended",
    returnReason: "กรุณาแนบใบเสนอราคาให้ครบ 3 ราย และระบุจำนวนผู้เข้าร่วมงานที่ชัดเจน",
    cycleHours: 6,
    createdAt: "06 Jun 2026 13:00",
    updatedAt: "07 Jun 2026 09:30",
  },
  {
    // Approved — safety equipment; shows GM-tier completed
    id: "EM-2026-007",
    title: "ขออนุมัติจัดซื้ออุปกรณ์ป้องกันส่วนบุคคล",
    requester: "นิรัน พงษ์ประเสริฐ",
    department: "GA",
    category: "general-purchase",
    amount: 12500,
    description: "ขออนุมัติจัดซื้อหมวกนิรภัย รองเท้าเซฟตี้ และถุงมือป้องกันสารเคมี สำหรับพนักงานโรงงาน 10 คน ตามมาตรฐาน ISO 45001:2018",
    budgetStatus: "in-budget",
    accountCode: "5302-001",
    budgetPlan: 30000,
    budgetUsed: 12500,
    status: "approved",
    workflowState: "Approved",
    currentStep: "General Manager",
    recommendedFinalApprover: "General Manager",
    recommendedRoute: ["Manager / Top Section", "General Manager"],
    selectedRoute: ["Manager / Top Section", "General Manager"],
    routeMode: "recommended",
    cycleHours: 17,
    createdAt: "01 Jun 2026 09:00",
    updatedAt: "02 Jun 2026 10:15",
  },
  {
    // Rejected (revision-allowed) — over budget; shows rejection + re-submit path
    id: "EM-2026-008",
    title: "ขออนุมัติจ้างที่ปรึกษาระบบคุณภาพ ISO",
    requester: "วิทย์ ตระกูลงาม",
    department: "QA",
    category: "service-contract",
    amount: 95000,
    description: "ขออนุมัติว่าจ้างบริษัทที่ปรึกษาเพื่อปรับปรุงระบบคุณภาพ ISO 9001:2015 และ IATF 16949 รองรับการตรวจประเมินประจำปีในเดือนสิงหาคม 2026",
    budgetStatus: "over-budget",
    accountCode: "5401-001",
    budgetPlan: 80000,
    budgetUsed: 0,
    status: "rejected",
    workflowState: "Rejected",
    currentStep: "Managing Director",
    recommendedFinalApprover: "Managing Director",
    recommendedRoute: ["Manager / Top Section", "General Manager", "Managing Director"],
    selectedRoute: ["Manager / Top Section", "General Manager", "Managing Director"],
    routeMode: "recommended",
    rejectReason: "งบประมาณเกินแผนที่ตั้งไว้ กรุณาทบทวนขอบเขตงานและเจรจาราคาใหม่ให้อยู่ในกรอบ แล้วยื่นขออนุมัติอีกครั้ง",
    rejectDisposition: "revision-allowed",
    cycleHours: 18,
    createdAt: "30 May 2026 15:00",
    updatedAt: "02 Jun 2026 14:05",
  },
];
